### ISSUE TITLE
Missing level tag?

### ISSUE THREAD

**Issue by Ralphaf** [Paul19988/Advanced-Slime-World-Manager#101]
**Describe the issue** Bedwars1058 plugin just gets disabled

**Spigot version** 1.17.1

**Plugin version** 2.7.0

**How to reproduce**

**Crash reports (if available)** 

[19:50:50 ERROR]: Error occurred while enabling BedWars1058 v${gitVer}21.12.1 (Is it up to date?)
java.lang.RuntimeException: Missing Level tag?
        at com.grinderwolf.swm.plugin.world.importer.WorldImporter.lambda$loadChunks$7(WorldImporter.java:188) ~[slimeworldmanager-plugin.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at com.grinderwolf.swm.plugin.world.importer.WorldImporter.loadChunks(WorldImporter.java:198) ~[slimeworldmanager-plugin.jar:?]
        at com.grinderwolf.swm.plugin.world.importer.WorldImporter.readFromDirectory(WorldImporter.java:68) ~[slimeworldmanager-plugin.jar:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.importWorld(SWMPlugin.java:414) ~[slimeworldmanager-plugin.jar:?]
        at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.convertWorld(SlimeAdapter.java:365) ~[bedwars-plugin-21.12.1.jar:?]
        at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.convertWorlds(SlimeAdapter.java:333) ~[bedwars-plugin-21.12.1.jar:?]
        at com.andrei1058.bedwars.BedWars.loadArenasAndSigns(BedWars.java:590) ~[bedwars-plugin-21.12.1.jar:?]
        at com.andrei1058.bedwars.BedWars.onEnable(BedWars.java:336) ~[bedwars-plugin-21.12.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[19:50:50 INFO]: [BedWars1058] Disabling BedWars1058 v${gitVer}21.12.1

**Comment by ComputerNerd100** [comment]
@Ralphaf At first glance this would appear to be a bedwars1058 issue
Please could you open an issue with them if you haven't already and let us know what they say
If they refer you back to us, please can you provide a zip or other archive containing a minimal version of your server setup (bedwars1058 and ASWM plugins and configs, plus your server jar and config) so that we can reproduce and look into this.

**Comment by Ralphaf** [comment]
@ComputerNerd100 Yeah, at first I asked them to help me, but they said to ask for help at ASWM community

**Comment by Ralphaf** [comment]
Where should I send the small version of my server?

**Comment by ComputerNerd100** [comment]
@Ralphaf You can upload it to here by dragging into the comment box, or if you join our discord (https://discord.gg/YevvsMa) you can pop it into the bug reports channel or DM it to me :)

**Comment by Ralphaf** [comment]
I'll dm you in a while

**Comment by Ralphaf** [comment]
Yeah nice.. I got no support, is there anyone else who can help me with this problem?

**Comment by Owen1212055** [comment]
Please send the worlds here, this seems to be some kind of “issue” with the converter.
