### ISSUE TITLE
EMPTY WORLD

### ISSUE THREAD

**Issue by aleexgheorghe** [Paul19988/Advanced-Slime-World-Manager#113]
**Describe the issue**
I am using the latest version of the plugin **pull/97** from the 1.18 branch, I asked if I could use it on my 1.17 server and I was told that I could, so I don't think that's a problem since it doesn't happen to everyone, only to some people.

**Spigot version**
Papper 1.17.1

**Plugin version**
[Las dev build ](https://prnt.sc/9tHIDXs2JUCF)

**How to reproduce**
All this happens when I enter and load the world, the weight of this is eight megabytes and appears as empty. However, an error appears in console that I will attach next.

```log
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) JOINSync REQUEST xSp3ctro_ 8263a595-bd74-46d5-ab9a-7b261501da8d
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK 0c4abfee-7975-4f3f-a664-8ffb468b9912 8263a595-bd74-46d5-ab9a-7b261501da8d
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL01 0c4abfee-7975-4f3f-a664-8ffb468b9912 8263a595-bd74-46d5-ab9a-7b261501da8d false
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) task is null
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL04 0c4abfee-7975-4f3f-a664-8ffb468b9912 8263a595-bd74-46d5-ab9a-7b261501da8d false
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) task is null
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL05 0c4abfee-7975-4f3f-a664-8ffb468b9912 8263a595-bd74-46d5-ab9a-7b261501da8d false
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) task is null
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL07 0c4abfee-7975-4f3f-a664-8ffb468b9912 8263a595-bd74-46d5-ab9a-7b261501da8d false
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) task is null
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL06 0c4abfee-7975-4f3f-a664-8ffb468b9912 8263a595-bd74-46d5-ab9a-7b261501da8d false
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) task is null
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL09 0c4abfee-7975-4f3f-a664-8ffb468b9912 8263a595-bd74-46d5-ab9a-7b261501da8d false
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) task is null
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL10 0c4abfee-7975-4f3f-a664-8ffb468b9912 8263a595-bd74-46d5-ab9a-7b261501da8d false
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) task is null
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL08 0c4abfee-7975-4f3f-a664-8ffb468b9912 8263a595-bd74-46d5-ab9a-7b261501da8d false
[12:50:05] [Thread-28/INFO]: [minebox-survival] (DEBUG) task is null
[12:50:06] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_LOAD bf78bf15-bc4c-4512-9d5e-e74f414c0630 8263a595-bd74-46d5-ab9a-7b261501da8d SVL06
[12:50:06] [Thread-28/INFO]: [minebox-survival] (DEBUG) Loading world data...
[12:50:06] [Thread-28/INFO]: [minebox-survival] (DEBUG) Slime loader selected: SurvivalSlimeLoader
[12:50:06] [Thread-28/INFO]: [minebox-survival] (DEBUG) STATUSSync UPDATE SVL06 1 WORLD_SERVER true
[12:50:06] [Craft Scheduler Thread - 77 - minebox-survival/INFO]: [minebox-survival] (DEBUG) Loading world...
[12:50:06] [Craft Scheduler Thread - 77 - minebox-survival/INFO]: [minebox-survival] (DEBUG) Setting world properties
[12:50:06] [Craft Scheduler Thread - 77 - minebox-survival/INFO]: [SWM] Loading world 8263a595-bd74-46d5-ab9a-7b261501da8d.
[12:50:06] [Craft Scheduler Thread - 77 - minebox-survival/INFO]: [SWM] World 8263a595-bd74-46d5-ab9a-7b261501da8d loaded in 265ms.
[12:50:06] [Craft Scheduler Thread - 77 - minebox-survival/INFO]: [minebox-survival] (DEBUG) Loading world... [DONE]
[12:50:06] [Server thread/INFO]: [minebox-survival] (DEBUG) Generating world...
[12:50:06] [Server thread/INFO]: -------- World Settings For [8263a595-bd74-46d5-ab9a-7b261501da8d] --------
[12:50:06] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Carrot Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Potato Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Vine Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Kelp Growth Modifier: 100%
[12:50:06] [Server thread/INFO]: Entity Activation Range: An 16 / Mo 16 / Ra 32 / Mi 12 / Tiv false
[12:50:06] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[12:50:06] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[12:50:06] [Server thread/INFO]: Max TNT Explosions: 100
[12:50:06] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:50:06] [Server thread/INFO]: Experience Merge Radius: 6.0
[12:50:06] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:50:06] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:50:06] [Server thread/INFO]: Item Merge Radius: 4.0
[12:50:06] [Server thread/INFO]: Item Despawn Rate: 6000
[12:50:06] [Server thread/INFO]: View Distance: 4
[12:50:06] [Server thread/INFO]: Arrow Despawn Rate: 300 Trident Respawn Rate:1200
[12:50:06] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:50:06] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:50:06] [Server thread/INFO]: Mob Spawn Range: 4
[12:50:06] [Server thread/INFO]: [minebox-survival] (DEBUG) Generating world... [DONE]
[12:50:06] [Server thread/INFO]: [minebox-survival] (DEBUG) Setting up world border...
[12:50:06] [Server thread/INFO]: [minebox-survival] (DEBUG) Completing task...
[12:50:06] [Server thread/INFO]: [minebox-survival] (DEBUG) Completing task... [DONE]
[12:50:06] [Thread-28/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_LOAD_COMPLETED bf78bf15-bc4c-4512-9d5e-e74f414c0630 false
[12:50:06] [Thread-28/INFO]: [minebox-survival] (DEBUG) task is null
[12:50:07] [User Authenticator #1/INFO]: UUID of player xSp3ctro_ is 8263a595-bd74-46d5-ab9a-7b261501da8d
[12:50:07] [Server thread/INFO]: xSp3ctro_[/207.188.137.163:57902] logged in with entity id 175 at ([main]2.6999999880790746, 112.0, -6.662956534784122)
[12:50:07] [Thread-28/INFO]: [minebox-survival] (DEBUG) PSERVERSyncro UPDATE xSp3ctro_,8263a595-bd74-46d5-ab9a-7b261501da8d,1648036207562,SVL06,CONNECTED
[12:50:07] [Craft Scheduler Thread - 89 - minebox-survival/WARN]: [minebox-survival] Loaded class com.digitalsynware.profiles.ProfileSystem from minebox-profile-system v1.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
[12:50:07] [Thread-28/INFO]: [minebox-survival] (DEBUG) CHATSync CHAT [⌘11]<br>HEROE<br>Yu014<br>»<br>Ah,<br>no<br>ahora<br>no<br>puedo<br>xd<spr>Yu014<spr>Yu014<spr>Nivel<br>⌘11<spr>Prestigio<br>0<spr>192237<spr>3078458.909444071<spr>1645560657961<spr>Chica<spr>null
[12:50:07] [Craft Scheduler Thread - 87 - minebox-profile-system/INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:2, serverValue:723622}] to database.mb-hispano.mb-api.es:27017
[12:50:10] [Server thread/INFO]: [minebox-survival] (DEBUG) GC Run
[12:50:10] [Server thread/INFO]: [minebox-survival] (DEBUG) GC Run [DONE]
[12:50:14] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to minebox-survival v1.0-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "com.digitalsynware.survival.world.common.SurvivalWorld.getWorldDataContainer()" because "sw" is null
	at com.digitalsynware.survival.player.listener.PlayerDeathListener.onEntityDamage(PlayerDeathListener.java:42) ~[minebox-survival-1.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor81.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.server.players.PlayerList.moveToWorld(PlayerList.java:917) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.server.players.PlayerList.moveToWorld(PlayerList.java:820) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:815) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleClientCommand(ServerGamePacketListenerImpl.java:2639) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.handle(ServerboundClientCommandPacket.java:24) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.handle(ServerboundClientCommandPacket.java:6) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:50:14] [Thread-28/INFO]: [minebox-survival] (DEBUG) SHOPSync UPDATE {§"item"§:§"GOLD_NUGGET",§"itemPrice"§:1.779936,§"minStock"§:,§"actualStock"§:31877,§"maxStock"§:000000,§"defaultPrice"§:6.0,§"type"§:§"NORMAL"§}
[12:50:14] [Thread-28/INFO]: [minebox-survival] (DEBUG) SHOPSync UPDATE {§"item"§:§"ROTTEN_FLESH",§"itemPrice"§:.17999999999999972,§"minStock"§:,§"actualStock"§:140878,§"maxStock"§:000000,§"defaultPrice"§:.0,§"type"§:§"NORMAL"§}
[12:50:15] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntityChest@88c1479) at -13,29,-1 (Block{minecraft:air}) where there was no entity tile!
[12:50:15] [Server thread/WARN]: Chunk coordinates: -16,-16
[12:50:15] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:860)
[12:50:15] [Server thread/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.nms.v1171.CustomWorldServer.lambda$createChunk$8(CustomWorldServer.java:309)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.Chunk.addEntities(Chunk.java:953)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerChunkMap.lambda$protoChunkToFullChunk$47(PlayerChunkMap.java:1418)
[12:50:15] [Server thread/WARN]: 	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[12:50:15] [Server thread/WARN]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[12:50:15] [Server thread/WARN]: 	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerChunkMap.lambda$protoChunkToFullChunk$48(PlayerChunkMap.java:1400)
[12:50:15] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[12:50:15] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkTaskQueueSorter.b(ChunkTaskQueueSorter.java:58)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1235)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1248)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:680)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.IChunkProvider.getChunkAt(IChunkProvider.java:14)
[12:50:15] [Server thread/WARN]: 	at io.papermc.paper.util.CollisionUtil.getCollisionsForBlocksOrWorldBorder(CollisionUtil.java:469)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.world.level.ICollisionAccess.noCollision(ICollisionAccess.java:41)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.moveToWorld(PlayerList.java:941)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.moveToWorld(PlayerList.java:820)
[12:50:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1066)
[12:50:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.teleport(CraftEntity.java:561)
[12:50:15] [Server thread/WARN]: 	at minebox-survival-1.0-SNAPSHOT.jar//com.digitalsynware.survival.world.listener.WorldProtectionListener.onMove(WorldProtectionListener.java:222)
[12:50:15] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor127.execute(Unknown Source)
[12:50:15] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:50:15] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[12:50:15] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:50:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1541)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInFlying.a(PacketPlayInFlying.java:114)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPosition.a(PacketPlayInFlying.java:42)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1450)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1428)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1421)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1399)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1310)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[12:50:15] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:50:15] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntityChest@2f6a8d15) at -11,29,-3 (Block{minecraft:air}) where there was no entity tile!
[12:50:15] [Server thread/WARN]: Chunk coordinates: -16,-16
[12:50:15] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.Chunk.setTileEntity(Chunk.java:860)
[12:50:15] [Server thread/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.nms.v1171.CustomWorldServer.lambda$createChunk$8(CustomWorldServer.java:309)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.Chunk.addEntities(Chunk.java:953)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerChunkMap.lambda$protoChunkToFullChunk$47(PlayerChunkMap.java:1418)
[12:50:15] [Server thread/WARN]: 	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[12:50:15] [Server thread/WARN]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[12:50:15] [Server thread/WARN]: 	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerChunkMap.lambda$protoChunkToFullChunk$48(PlayerChunkMap.java:1400)
[12:50:15] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[12:50:15] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkTaskQueueSorter.b(ChunkTaskQueueSorter.java:58)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1235)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1248)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.level.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:680)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.world.level.chunk.IChunkProvider.getChunkAt(IChunkProvider.java:14)
[12:50:15] [Server thread/WARN]: 	at io.papermc.paper.util.CollisionUtil.getCollisionsForBlocksOrWorldBorder(CollisionUtil.java:469)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.world.level.ICollisionAccess.noCollision(ICollisionAccess.java:41)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.moveToWorld(PlayerList.java:941)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.moveToWorld(PlayerList.java:820)
[12:50:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1066)
[12:50:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.teleport(CraftEntity.java:561)
[12:50:15] [Server thread/WARN]: 	at minebox-survival-1.0-SNAPSHOT.jar//com.digitalsynware.survival.world.listener.WorldProtectionListener.onMove(WorldProtectionListener.java:222)
[12:50:15] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor127.execute(Unknown Source)
[12:50:15] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:50:15] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[12:50:15] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:50:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1541)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInFlying.a(PacketPlayInFlying.java:114)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPosition.a(PacketPlayInFlying.java:42)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1450)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1428)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1421)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1399)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1310)
[12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[12:50:15] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:50:16] [Server thread/INFO]: [minebox-survival] World is not empty. Unload task cancelled.
[12:50:17] [Thread-28/INFO]: [minebox-survival] (DEBUG) CHATSync CHAT [

**Comment by Owen1212055** [comment]
Yeah can confirm this issue, still working that out.

**Comment by aleexgheorghe** [comment]
Thanks, I'll be waiting

**Comment by aleexgheorghe** [comment]
When shutting down the server, this problem also occurs.

![image](https://user-images.githubusercontent.com/46347629/159697344-5f0a995b-cfe8-48de-b1b9-a4f1b19eb136.png)

**Comment by Owen1212055** [comment]
Fixed in https://github.com/Paul19988/Advanced-Slime-World-Manager/pull/97/commits/612a30d1a4fd6db52370b664350718f1369b2ee1
