### ISSUE TITLE
CORRUPT WORLD, weight more than 100mb

### ISSUE THREAD

**Issue by aleexgheorghe** [Paul19988/Advanced-Slime-World-Manager#115]
**Describe the issue**
I was testing the latest version and apparently a user had his world magically corrupted. When I noticed it, I checked that his .slime was over 100mb and when he tried to load the world the following error appeared 
```java

Save New Duplicate & Edit Just Text Twitter
[10:25:39] [Thread-28/INFO]: [minebox-survival] (DEBUG) Slime loader selected: SurvivalSlimeLoader
[10:25:39] [Thread-28/INFO]: [minebox-survival] (DEBUG) STATUSSync UPDATE SVL10 1 WORLD_SERVER true
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/INFO]: [minebox-survival] (DEBUG) Loading world...
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/INFO]: [minebox-survival] (DEBUG) Setting world properties
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/INFO]: [SWM] Loading world 59fcc1b9-a852-4593-b1f3-aa538bf5f849.
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: com.grinderwolf.swm.api.exceptions.CorruptedWorldException: World 59fcc1b9-a852-4593-b1f3-aa538bf5f849 seems to be corrupted
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.deserializeWorld(v1_9SlimeWorldFormat.java:112)
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.plugin.loaders.slime.SlimeWorldReaderRegistry.readWorld(SlimeWorldReaderRegistry.java:50)
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:265)
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: 	at minebox-survival-1.0-SNAPSHOT.jar//com.digitalsynware.survival.world.processing.SurvivalWorldLoadProcess$1.run(SurvivalWorldLoadProcess.java:48)
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:25:39] [Craft Scheduler Thread - 5 - minebox-survival/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:25:43] [Server thread/INFO]: [minebox-survival] (DEBUG) GC Run
[10:25:43] [Server thread/INFO]: [minebox-survival] (DEBUG) GC Run [DONE]
[10:25:54] [Thread-28/INFO]: [minebox-survival] (DEBUG) STATUSSync REQUEST
[10:25:54] [Thread-28/INFO]: [minebox-survival] (DEBUG) STATUSSync UPDATE SVRC01 0 RESOURCE_SERVER true
[10:25:54] [Thread-28/INFO]: [minebox-survival] (DEBUG) STATUSSync UPDATE SVMP01 0 PVPMINE_SERVER true
[10:25:54] [Thread-28/INFO]: [minebox-survival] (DEBUG) STATUSSync UPDATE SVL01 3 WORLD_SERVER true
```

In fact, the total weight of the world is shown here. All worlds usually weigh around 8mb and this one magically weighs 100mb. 

```bash
root@vcloud4:/var/survival/worlds/5# ls -lh 59fcc1b9-a852-4593-b1f3-aa538bf5f849.slime 
-rw-r--r-- 1 root root 100M Mar 24 10:22 59fcc1b9-a852-4593-b1f3-aa538bf5f849.slime
```

We save the world periodically every five minutes (this has no influence since with previous versions of the plugin nothing happened to us) and the saving is done as follows: https://paste.minebox.es/efebagokok.typescript

**Spigot version**
Paper 1.17.1

**Plugin version**
Last build

**Comment by Owen1212055** [comment]
The reason for this happened was unknown, however, if this is run into again it will be looked into further.

This was due to a GIANT chunk bitset being created, meaning there were far-away chunks loaded in a slimeworld.
