### ISSUE TITLE
WORLD not load

### ISSUE THREAD

**Issue by aleexgheorghe** [Paul19988/Advanced-Slime-World-Manager#116]
**Describe the issue**
I have been updating the plugin these last days and apparently a user is giving an error when loading said world.

**Spigot version**
Last version paper 1.17.1

**Plugin version**
Last dev build

**Logs**
```java
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) JOINSync REQUEST Skoli_ 95dcf364-cb13-36bf-8e54-b057e9b4594f
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL01 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) Data added to 44d890d6-9105-41e6-b82f-6e6a8918c505: SVL01-false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) 1 >= 15
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL06 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) Data added to 44d890d6-9105-41e6-b82f-6e6a8918c505: SVL06-false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) 2 >= 15
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL05 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) Data added to 44d890d6-9105-41e6-b82f-6e6a8918c505: SVL05-false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) 3 >= 15
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL07 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) Data added to 44d890d6-9105-41e6-b82f-6e6a8918c505: SVL07-false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) 4 >= 15
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL04 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) Data added to 44d890d6-9105-41e6-b82f-6e6a8918c505: SVL04-false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) 5 >= 15
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL09 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) Data added to 44d890d6-9105-41e6-b82f-6e6a8918c505: SVL09-false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) 6 >= 15
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL02 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) Data added to 44d890d6-9105-41e6-b82f-6e6a8918c505: SVL02-false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) 7 >= 15
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL03 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) Data added to 44d890d6-9105-41e6-b82f-6e6a8918c505: SVL03-false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) 8 >= 15
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL10 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) Data added to 44d890d6-9105-41e6-b82f-6e6a8918c505: SVL10-false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) 9 >= 15
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_CHECK_RESPONSE SVL08 44d890d6-9105-41e6-b82f-6e6a8918c505 95dcf364-cb13-36bf-8e54-b057e9b4594f false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) Data added to 44d890d6-9105-41e6-b82f-6e6a8918c505: SVL08-false
[18:22:56] [Thread-25/INFO]: [minebox-survival] (DEBUG) 10 >= 15
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/INFO]: [minebox-survival] (DEBUG) Checking if task was completed
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/INFO]: [minebox-survival] (DEBUG) 10 >= 15
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/INFO]: [minebox-survival] (DEBUG) Task not completed, completing...
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/INFO]: [minebox-survival] (DEBUG) Task not completed, completing... [DONE]
[18:22:57] [Thread-25/INFO]: [minebox-survival] (DEBUG) CompletableTaskManager WORLD_LOAD 59951a66-88c7-4c33-b76e-4b27fc076512 95dcf364-cb13-36bf-8e54-b057e9b4594f SVL01
[18:22:57] [Thread-25/INFO]: [minebox-survival] (DEBUG) Loading world data...
[18:22:57] [Thread-25/INFO]: [minebox-survival] (DEBUG) Slime loader selected: SurvivalSlimeLoader
[18:22:57] [Thread-25/INFO]: [minebox-survival] (DEBUG) STATUSSync UPDATE SVL01 3 WORLD_SERVER true
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/INFO]: [minebox-survival] (DEBUG) Loading world...
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/INFO]: [minebox-survival] (DEBUG) Setting world properties
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/INFO]: [SWM] Loading world 95dcf364-cb13-36bf-8e54-b057e9b4594f.
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: java.io.IOException: TAG_End found without a TAG_Compound/TAG_List tag preceding it.
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.internal.nbt.stream.NBTInputStream.readTagPayload(NBTInputStream.java:180)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.internal.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:159)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.internal.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:136)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readCompoundTag(v1_9SlimeWorldFormat.java:440)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readChunkSections(v1_9SlimeWorldFormat.java:394)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readChunks(v1_9SlimeWorldFormat.java:284)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.deserializeWorld(v1_9SlimeWorldFormat.java:126)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.plugin.loaders.slime.SlimeWorldReaderRegistry.readWorld(SlimeWorldReaderRegistry.java:50)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at slimeworldmanager-plugin.jar//com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:270)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at minebox-survival-1.0-SNAPSHOT.jar//com.digitalsynware.survival.world.processing.SurvivalWorldLoadProcess$1.run(SurvivalWorldLoadProcess.java:48)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:22:57] [Craft Scheduler Thread - 357 - minebox-survival/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
Thank you very much, I will be waiting.

**Comment by Owen1212055** [comment]
Please report if someone like this comes up again, it seems this was a weird corruption with the palette of a chunk. It's possible I can prevent this chunk from being loaded in the future instead of fully cancelling the loading of the world.

**Comment by aleexgheorghe** [comment]
> Please report if someone like this comes up again, it seems this was a weird corruption with the palette of a chunk. It's possible I can prevent this chunk from being loaded in the future instead of fully cancelling the loading of the world.


Hello! It’s really incredible that it really doesn’t load the whole world becomes a chunk. This aggressive action causes some users to lose their world in some way without being able to recover their belongings.

Thank you very much.

**Comment by t3rry327** [comment]
We cannot do anything with this. Maybe u can check if some of ur plugins is trying to modify chunks accessing the world at the same time

> > Please report if someone like this comes up again, it seems this was a weird corruption with the palette of a chunk. It's possible I can prevent this chunk from being loaded in the future instead of fully cancelling the loading of the world.
> 
> Hello! It’s really incredible that it really doesn’t load the whole world becomes a chunk. This aggressive action causes some users to lose their world in some way without being able to recover their belongings.
> 
> Thank you very much.

**Comment by aleexgheorghe** [comment]
This problem has happened because I have been testing dev-builds and possibly it has happened. Next time I will not hesitate to make backups!
