### ISSUE TITLE
Worlds do not load

### ISSUE THREAD

**Issue by samfces** [Paul19988/Advanced-Slime-World-Manager#122]
**Describe the issue**
When I try to load a world using the ASWM API I get the following error in console:
```
java.lang.NegativeArraySizeException: -472757874
	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.deserializeWorld(v1_9SlimeWorldFormat.java:66) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.loaders.slime.SlimeWorldReaderRegistry.readWorld(SlimeWorldReaderRegistry.java:50) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:271) ~[slimeworldmanager-plugin.jar:?]
	at com.digitalsynware.survival.world.processing.SurvivalWorldLoadProcess$1.run(SurvivalWorldLoadProcess.java:56) ~[minebox-survival-1.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
**Spigot version**
Paper version git-Paper-409 (MC: 1.17.1)

**Plugin version**
It is one of the latest builds. The /swm version command does not show the version.
![image](https://user-images.githubusercontent.com/26687602/164800938-d4d77b70-44d5-46db-9002-d2ee9b084a96.png)

**How to reproduce**
It is simply a matter of trying to load the attached world: 
[c2af8f8a-a88c-3076-91b8-716aa0eadbff.zip](https://github.com/Paul19988/Advanced-Slime-World-Manager/files/8544307/c2af8f8a-a88c-3076-91b8-716aa0eadbff.zip)

**Comment by Owen1212055** [comment]
Bitset appears to be too big, will need to update the format to fix this.
