### ISSUE TITLE
Failed to override methods from class net.minecraft.server.level.PlayerChunkMap

### ISSUE THREAD

**Issue by AoElite** [Paul19988/Advanced-Slime-World-Manager#155]
**Describe the issue**
Error on start up when using latest paper.

**Spigot version**
This server is running Paper version git-Paper-177 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 1bbd273)

**Plugin version**
slimeworldmanager-classmodifier-2.10.0-SNAPSHOT.jar
slimeworldmanager-plugin-2.10.0-SNAPSHOT.jar
Git: 8fa7819b07a51ce606724d0a2d4cad6203a3c801

**How to reproduce**
Use specified jar and start the server.
(Also yes `-javaagent:slimeworldmanager-classmodifier-2.10.0-SNAPSHOT.jar` is included in the start script)

**Crash reports (if available)**
```
[19:38:06 ERROR]: [STDERR] [com.grinderwolf.swm.clsm.NMSTransformer] Failed to override methods from class net.minecraft.server.level.PlayerChunkMap.
[19:38:06 WARN]: javassist.CannotCompileException: Method a
[19:38:06 WARN]:        at com.grinderwolf.swm.clsm.NMSTransformer.transform(NMSTransformer.java:261)
[19:38:06 WARN]:        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
[19:38:06 WARN]:        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
[19:38:06 WARN]:        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
[19:38:06 WARN]:        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[19:38:06 WARN]:        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[19:38:06 WARN]:        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[19:38:06 WARN]:        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
[19:38:06 WARN]:        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
[19:38:06 WARN]:        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
[19:38:06 WARN]:        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
[19:38:06 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
[19:38:06 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[19:38:06 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19:38:06 WARN]:        at net.minecraft.world.level.World.<init>(World.java:278)
[19:38:06 WARN]:        at net.minecraft.server.level.WorldServer.<init>(WorldServer.java:526)
[19:38:06 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:586)
[19:38:06 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[19:38:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[19:38:06 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[19:38:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[19:38:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[19:38:06 WARN]: Caused by: javassist.CannotCompileException: [source error] no such field: $0/q
[19:38:06 WARN]:        at javassist.CtBehavior.insertBefore(CtBehavior.java:806)
[19:38:06 WARN]:        at javassist.CtBehavior.insertBefore(CtBehavior.java:766)
[19:38:06 WARN]:        at com.grinderwolf.swm.clsm.NMSTransformer.transform(NMSTransformer.java:247)
[19:38:06 WARN]:        ... 21 more
[19:38:06 WARN]: Caused by: compile error: no such field: $0/q
[19:38:06 WARN]:        at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:288)
[19:38:06 WARN]:        at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:941)
[19:38:06 WARN]:        at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:929)
[19:38:06 WARN]:        at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:831)
[19:38:06 WARN]:        at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:605)
[19:38:06 WARN]:        at javassist.compiler.ast.Expr.accept(Expr.java:71)
[19:38:06 WARN]:        at javassist.compiler.JvstTypeChecker.atMethodArgs(JvstTypeChecker.java:235)
[19:38:06 WARN]:        at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:763)
[19:38:06 WARN]:        at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:723)
[19:38:06 WARN]:        at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
[19:38:06 WARN]:        at javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
[19:38:06 WARN]:        at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
[19:38:06 WARN]:        at javassist.compiler.CodeGen.compileBooleanExpr(CodeGen.java:260)
[19:38:06 WARN]:        at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:414)
[19:38:06 WARN]:        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:385)
[19:38:06 WARN]:        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[19:38:06 WARN]:        at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
[19:38:06 WARN]:        at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[19:38:06 WARN]:        at javassist.compiler.Javac.compileStmnt(Javac.java:578)
[19:38:06 WARN]:        at javassist.CtBehavior.insertBefore(CtBehavior.java:786)
[19:38:06 WARN]:        ... 23 more
```

**Comment by Paul19988** [comment]
We are not compatible with the latest paper due to the MASSIVE chunk rewrite

**Comment by AoElite** [comment]
Are you dropping paper support entirely?

**Comment by Owen1212055** [comment]
We will be soon! :) (hopefully)

**Comment by vytskalt** [comment]
Are you gonna drop support for Spigot after making it work with the chunk rewrite?
