### ISSUE TITLE
help me pls

### ISSUE THREAD

**Issue by Luisitohh** [Paul19988/Advanced-Slime-World-Manager#169]
**Describe the issue** dont start

**Spigot version** 1.19.4

**Plugin version** 2.8.0

**How to reproduce** when i use sh start.sh

**Crash reports (if available)**
p classpath has been appended
java.lang.UnsupportedOperationException: 1.19.4
        at com.grinderwolf.swm.clsm.NMSTransformer.getNMSVersion(NMSTransformer.java:164)
        at com.grinderwolf.swm.clsm.NMSTransformer.transform(NMSTransformer.java:187)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:791)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:686)

This is my SH
/usr/lib/jvm/java-17-openjdk-amd64/bin/java -Xms0G -Xmx2G -DPaper.IgnoreJavaVersion=true -javaagent:slimeworldmanager-classmodifier-2.8.0-SNAPSHOT.jar -jar spigot.jar nogui

**Comment by akcelerat0r** [comment]
You have to try the paperclip spigot from the discord server, under #new builds there are the downloads for it.
If you want add me on Discord to, I'm on the Server called AKcel

**Comment by Paul19988** [comment]
AdvancedSlimePaper has replaced ASWM for 1.19.4:
https://github.com/InfernalSuite/AdvancedSlimePaper
