### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by nazmiyigitefe** [Paul19988/Advanced-Slime-World-Manager#173]
**Describe the issue**
It does not supports 1.20.
**Spigot version**
1.20 - Purpur
**Plugin version**
2.8.0-beta
**How to reproduce**
Just setup the plugin and classmodifier on a 1.20 server.
**Crash reports (if available)**
```[22:48:55] [Server thread/INFO]: [SlimeWorldManager] Loading server plugin SlimeWorldManager v2.8.0
[22:48:55] [Server thread/INFO]: [SWM] SlimeWorldManager does not support Spigot 3463!
[22:48:59] [Server thread/INFO]: [SlimeWorldManager] Enabling SlimeWorldManager v2.8.0
[22:48:59] [Server thread/ERROR]: Error occurred while enabling SlimeWorldManager v2.8.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.grinderwolf.swm.nms.SlimeNMS.getSlimeWorld(org.bukkit.World)" because the return value of "com.grinderwolf.swm.plugin.SWMPlugin.getNms()" is null
	at com.grinderwolf.swm.plugin.SWMPlugin.lambda$onDisable$1(SWMPlugin.java:153) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.onDisable(SWMPlugin.java:157) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.onEnable(SWMPlugin.java:123) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.jar:git-Purpur-1988]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.jar:git-Purpur-1988]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:577) ~[purpur-1.20.jar:git-Purpur-1988]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:488) ~[purpur-1.20.jar:git-Purpur-1988]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.jar:git-Purpur-1988]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.jar:git-Purpur-1988]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.20.jar:git-Purpur-1988]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.jar:git-Purpur-1988]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.jar:git-Purpur-1988]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nazmiyigitefe** [comment]
Also there are library errors after the setup, like this:

```[22:53:57] [Server thread/WARN]: java.nio.file.NoSuchFileException: C:\Users\Administrator\Desktop\MC\Lydoria%20Tekblok%20-%201.20\libraries\com\googlecode\json-simple\json-simple\1.1.1\json-simple-1.1.1.jar
[22:53:57] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[22:53:57] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[22:53:57] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[22:53:57] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
[22:53:57] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
[22:53:57] [Server thread/WARN]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
[22:53:57] [Server thread/WARN]: 	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
[22:53:57] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
[22:53:57] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
[22:53:57] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
[22:53:57] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
[22:53:57] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:143)
[22:53:57] [Server thread/WARN]: 	at com.grinderwolf.swm.clsm.NMSTransformer.transform(NMSTransformer.java:179)
[22:53:57] [Server thread/WARN]: 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
[22:53:57] [Server thread/WARN]: 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
[22:53:57] [Server thread/WARN]: 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
[22:53:57] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[22:53:57] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[22:53:57] [Server thread/WARN]: 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[22:53:57] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
[22:53:57] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
[22:53:57] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
[22:53:57] [Server thread/WARN]: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
[22:53:57] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
[22:53:57] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[22:53:57] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:574)
[22:53:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[22:53:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[22:53:57] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22:53:57] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.metrics.Metrics.getServerData(Metrics.java:219)
[22:53:57] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.metrics.Metrics.submitData(Metrics.java:240)
[22:53:57] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.metrics.Metrics.access$100(Metrics.java:30)
[22:53:57] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.metrics.Metrics$1.lambda$run$0(Metrics.java:154)
[22:53:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:53:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1507)
[22:53:57] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:484)
[22:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[22:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[22:53:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[22:53:57] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by bridgelol** [comment]
I'm afraid this repo is no longer being maintained, however, the InfernalSuite team has already pushed a 1.20 update to ASP (https://github.com/InfernalSuite/AdvancedSlimePaper).

**Comment by Paul19988** [comment]
Issue closed, please use ASP.
