### ISSUE TITLE
java.lang.NoSuchMethodError (plugin.createEmptyWorld)

### ISSUE THREAD

**Issue by Semisol** [Paul19988/Advanced-Slime-World-Manager#24]
**Describe the issue**
```
[17:11:58 WARN]: [PrivateWorldService] Plugin PrivateWorldService v1.0-SNAPSHOT generated an exception while executing task 9720
java.lang.NoSuchMethodError: com.grinderwolf.swm.api.world.properties.SlimePropertyMap.toCompound()Lcom/grinderwolf/swm/internal/com/flowpowered/nbt/CompoundTag;
        at com.grinderwolf.swm.nms.CraftSlimeWorld.serialize(CraftSlimeWorld.java:128) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.createEmptyWorld(SWMPlugin.java:291) ~[?:?]
        at dev.semisol.customstuff.privateworldservice.Events.lambda$playerJoinEvent$0(Events.java:59) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-439]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-439]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-439]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

```
**Spigot version**
1.16.5 Paper (439)
**Plugin version**
2.5.3
**How to reproduce**
(Simplified version of my code)
```java
String world = "test"; // Fetched from redis, is a valid string
SlimePropertyMap properties = new SlimePropertyMap();
properties.setString(SlimeProperties.DIFFICULTY, "easy");
properties.setInt(SlimeProperties.SPAWN_X, 0);
properties.setInt(SlimeProperties.SPAWN_Y, 64);
properties.setInt(SlimeProperties.SPAWN_Z, 0);
properties.setString(SlimeProperties.ENVIRONMENT, "normal");
properties.setString(SlimeProperties.ENVIRONMENT, "normal");
SlimePlugin plugin = (SlimePlugin) Bukkit.getPluginManager().getPlugin("SlimeWorldManager");
SlimeLoader loader = plugin.getLoader("mysql");
plugin.createEmptyWorld(loader, world, false, properties);
```
**Crash reports (if available)**
None

(Using the SWM API repository, while using this for the plugin/classmodifier.)

**Comment by Paul19988** [comment]
@Semisol What is at line 59 of events?

**Comment by Semisol** [comment]
> @Semisol What is at line 59 of events?

The last line in the code I showed.

**Comment by Semisol** [comment]
(The title was too long)

**Comment by Paul19988** [comment]
https://ci.rapture.pw/browse/ASWM-ASWM10-21/artifact/shared/output/

Could you try to use the versions from this build as the latest is 2.5.4

**Comment by Semisol** [comment]
> [ci.rapture.pw/browse/ASWM-ASWM10-21/artifact/shared/output](https://ci.rapture.pw/browse/ASWM-ASWM10-21/artifact/shared/output/)
> 
> Could you try to use the versions from this build as the latest is 2.5.4

Will check that build, if still failing will tell.

**Comment by Semisol** [comment]
Not so different
```
[17:32:28 WARN]: [PrivateWorldService] Plugin PrivateWorldService v1.0-SNAPSHOT generated an exception while executing task 544
java.lang.NoSuchMethodError: com.grinderwolf.swm.api.world.properties.SlimePropertyMap.toCompound()Lcom/grinderwolf/swm/internal/com/flowpowered/nbt/CompoundTag;
        at com.grinderwolf.swm.nms.CraftSlimeWorld.serialize(CraftSlimeWorld.java:133) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.createEmptyWorld(SWMPlugin.java:291) ~[?:?]
        at dev.semisol.customstuff.privateworldservice.Events.lambda$playerJoinEvent$0(Events.java:59) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-439]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-439]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-439]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```
(code still the same)

**Comment by Paul19988** [comment]
Could you try the following versions:

[ASWM.zip](https://github.com/Paul19988/Advanced-Slime-World-Manager/files/5860798/ASWM.zip)

**Comment by Semisol** [comment]
> Could you try the following versions:
> 
> [ASWM.zip](https://github.com/Paul19988/Advanced-Slime-World-Manager/files/5860798/ASWM.zip)

Will do

**Comment by Semisol** [comment]
```
[18:30:33 WARN]: [PrivateWorldService] Plugin PrivateWorldService v1.0-SNAPSHOT generated an exception while executing task 544
java.lang.NoSuchMethodError: com.grinderwolf.swm.api.world.properties.SlimePropertyMap.toCompound()Lcom/grinderwolf/swm/internal/com/flowpowered/nbt/CompoundTag;
        at com.grinderwolf.swm.nms.CraftSlimeWorld.serialize(CraftSlimeWorld.java:133) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.createEmptyWorld(SWMPlugin.java:291) ~[?:?]
        at dev.semisol.customstuff.privateworldservice.Events.lambda$playerJoinEvent$0(Events.java:59) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-439]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-439]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-439]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

```

**Comment by Semisol** [comment]
Oh wait.

**Comment by Semisol** [comment]
Nvm

**Comment by Paul19988** [comment]
Out of curiosity to cover all bases, how are you importing SWM into your project?

**Comment by Semisol** [comment]
I use the old maven repository.
But, it is not shaded.

**Comment by Paul19988** [comment]
It's possible that could be the cause as that maven repo doesn't actually work/exist anymore

**Comment by Semisol** [comment]
I use it so the compilation works, not anything else.
Also, the error is internal in SWM. 
(`        at com.grinderwolf.swm.nms.CraftSlimeWorld.serialize(CraftSlimeWorld.java:133) ~[?:?]`) first line

**Comment by Semisol** [comment]
@Paul19988 Do you have a maven repo?

**Comment by Paul19988** [comment]
Yep we sure do,

```
<repository>
    <id>rapture-snapshots</id>
    <url>https://repo.rapture.pw/repository/maven-snapshots/</url>
</repository>

<dependency>
    <groupId>com.grinderwolf</groupId>
    <artifactId>slimeworldmanager-api</artifactId>
    <version>2.5.4-SNAPSHOT</version>
    <scope>provided</scope>
</dependency>
```

**Comment by Paul19988** [comment]
Did using this repo help fix this?

**Comment by Semisol** [comment]
Will try.

**Comment by Semisol** [comment]
Works!

**Comment by Paul19988** [comment]
Aha success! must be something changed in the API versions, I'll go ahead and close up this issue now

**Comment by Semisol** [comment]
> Aha success! must be something changed in the API versions, I'll go ahead and close up this issue now

Thank you.
