### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by morgan2233** [Paul19988/Advanced-Slime-World-Manager#29]
Won't start

Paper 1.16.5 #529

2.5.3

Follow Install steps, start server

```
[14:23:18 INFO]: Hub2 > [SlimeWorldManager] Loading SlimeWorldManager v2.5.3-SNAPSHOT
[14:23:18 INFO]: Hub2 > getNMSBridge - isPaperMC: true
[14:23:19 INFO]: Hub2 > Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[14:23:19 ERROR]: Hub2 > Main thread terminated by WatchDog due to hard crash
[14:23:19 INFO]: Hub2 > java.lang.ThreadDeath: null
[14:23:19 INFO]: Hub2 >         at java.lang.Thread.stop(Thread.java:942) [?:?]
[14:23:19 INFO]: Hub2 >         at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:757) ~[patched_1.16.5.jar:git-Paper-529]
[14:23:19 INFO]: Hub2 >         at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:706) ~[patched_1.16.5.jar:git-Paper-529]
[14:23:19 INFO]: Hub2 >         at net.minecraft.server.v1_16_R3.MinecraftServer.close(MinecraftServer.java:729) ~[patched_1.16.5.jar:git-Paper-529]
[14:23:19 INFO]: Hub2 >         at org.bukkit.craftbukkit.v1_16_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:28) ~[patched_1.16.5.jar:git-Paper-529]
```

**Comment by CDFN** [comment]
Read install guide first. You're missing javaagent

**Comment by morgan2233** [comment]
Sorry! Using SubServers for better server management and I didn't realize SubServers Bungee caches the server file. I did add the javagent argument but it didn't apply; quick bungee restart and Works now!
