### ISSUE TITLE
Error when loading/creating world

### ISSUE THREAD

**Issue by morgan2233** [Paul19988/Advanced-Slime-World-Manager#30]
Error when trying to create OR load world

Paper - 1.16.5 #529

2.5.3

create world or load world

```
[15:06:49 WARN]: Hub2 > [SlimeWorldManager] Plugin SlimeWorldManager v2.5.3-SNAPSHOT generated an exception while executing task 70919
[15:06:49 INFO]: Hub2 > java.lang.UnsatisfiedLinkError: 'long com.github.luben.zstd.Zstd.decompress(byte[], byte[])'
[15:06:49 INFO]: Hub2 >         at com.github.luben.zstd.Zstd.decompress(Native Method) ~[?:?]
[15:06:49 INFO]: Hub2 >         at com.grinderwolf.swm.plugin.loaders.LoaderUtils.deserializeWorld(LoaderUtils.java:218) ~[?:?]
[15:06:49 INFO]: Hub2 >         at com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:250) ~[?:?]
[15:06:49 INFO]: Hub2 >         at com.grinderwolf.swm.plugin.commands.sub.LoadWorldCmd.lambda$onCommand$1(LoadWorldCmd.java:76) ~[?:?]
[15:06:49 INFO]: Hub2 >         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-529]
[15:06:49 INFO]: Hub2 >         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-529]
[15:06:49 INFO]: Hub2 >         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-529]
[15:06:49 INFO]: Hub2 >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
[15:06:49 INFO]: Hub2 >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
[15:06:49 INFO]: Hub2 >         at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Paul19988** [comment]
- Temporarily disable FAWE
- Create a world on ASWM and have it load on startup
- Then you can put FAWE back in

**Comment by wasn325** [comment]
A possible fix for this issue could be adding Fawe as softdepend to the aswm plugin. I did it and aswm works fine with fawe

**Comment by wasn325** [comment]
...at least for me (not sure about other people)
