### ISSUE TITLE
load worlds error

### ISSUE THREAD

**Issue by minecraft7net** [Paul19988/Advanced-Slime-World-Manager#32]
same error with 2.5.3 with/without fawe

[17:51:56] [Server thread/INFO]: [SlimeWorldManager] Loading SlimeWorldManager v2.5.0-SNAPSHOT
[17:51:57] [Server thread/INFO]: [SWM] Loading world Lobby.
[17:51:57] [Server thread/INFO]: [SWM] Missing world upgrader for version 4. World will not be upgraded.
[17:51:57] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing SlimeWorldManager v2.5.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at com.grinderwolf.swm.plugin.upgrade.v1_14.v1_14WorldUpgrade.upgrade(v1_14WorldUpgrade.java:50) ~[?:?]
        at com.grinderwolf.swm.plugin.upgrade.WorldUpgrader.upgradeWorld(WorldUpgrader.java:31) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:245) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.loadWorlds(SWMPlugin.java:186) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.onLoad(SWMPlugin.java:74) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Paper-497]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-497]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941) ~[patched_1.16.5.jar:git-Paper-497]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Paul19988** [comment]
Make sure to update your Paper as you're nearly 100 versions behind now (if you can)

Also ASWM does not support any world that is not already on 1.16.x.

**Comment by minecraft7net** [comment]
[18:54:07] [Server thread/INFO]: This server is running Paper version git-Paper-570 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

[18:54:14] [Server thread/INFO]: [SlimeWorldManager] Loading SlimeWorldManager v2.5.0-SNAPSHOT
[18:54:14] [Server thread/INFO]: [SWM] Loading world Lobby.
[18:54:14] [Server thread/INFO]: [SWM] Missing world upgrader for version 4. World will not be upgraded.
[18:54:14] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing SlimeWorldManager v2.5.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at com.grinderwolf.swm.plugin.upgrade.v1_14.v1_14WorldUpgrade.upgrade(v1_14WorldUpgrade.java:50) ~[?:?]
        at com.grinderwolf.swm.plugin.upgrade.WorldUpgrader.upgradeWorld(WorldUpgrader.java:31) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:245) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.loadWorlds(SWMPlugin.java:186) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.onLoad(SWMPlugin.java:74) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Paper-570]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:251) ~[patched_1.16.5.jar:git-Paper-570]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-570]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-570]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by minecraft7net** [comment]
[18:56:36] [Server thread/INFO]: [SWM] Loading world Lobby.
[18:56:36] [Server thread/INFO]: [SWM] Missing world upgrader for version 4. World will not be upgraded.
[18:56:36] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing SlimeWorldManager v2
.5.3-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at com.grinderwolf.swm.plugin.upgrade.v1_14.v1_14WorldUpgrade.upgrade(v1_14WorldUpgrade.java:50) ~[?:?]
        at com.grinderwolf.swm.plugin.upgrade.WorldUpgrader.upgradeWorld(WorldUpgrader.java:33) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:255) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.loadWorlds(SWMPlugin.java:196) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.onLoad(SWMPlugin.java:82) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Pape
r-570]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:251) ~[patched_1.16.5.jar:git-Paper
-570]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-5
70]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git
-Paper-570]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Paul19988** [comment]
This still does not change the fact that you're using an older world, please update it to 1.16.x with SWM first then you can use ASWM.

**Comment by minecraft7net** [comment]
thank You - but if i understand correctly SWM if only for 1.14 max ?

**Comment by Paul19988** [comment]
https://discord.gg/FYhZ3WYm

Join the SWM discord and look in the announcements channel for the latest version
