### ISSUE TITLE
Cannot create worlds with FastAsyncWorldEdit installed.

### ISSUE THREAD

**Issue by levahmc** [Paul19988/Advanced-Slime-World-Manager#34]
I cannot create worlds to file, nor any db if FastAsyncWorldEdit is installed.

Server: Purpur 1.16.5

Plugin: 2.5.3-SNAPSHOT

Reproduce: Create a world with FastAsyncWorldEdit installed.

`[03:40:27 WARN]: [SlimeWorldManager] Loaded class com.github.luben.zstd.util.Native from FastAsyncWorldEdit v1.16-581;dd65cff which is not a depend, softdepend or loadbefore of this plugin.
[03:40:27 WARN]: [SlimeWorldManager] Plugin SlimeWorldManager v2.5.3-SNAPSHOT generated an exception while executing task 22
java.lang.UnsatisfiedLinkError: 'long com.github.luben.zstd.Zstd.compressBound(long)'
        at com.github.luben.zstd.Zstd.compressBound(Native Method) ~[?:?]
        at com.github.luben.zstd.Zstd.compress(Zstd.java:612) ~[?:?]
        at com.github.luben.zstd.Zstd.compress(Zstd.java:601) ~[?:?]
        at com.grinderwolf.swm.nms.CraftSlimeWorld.serialize(CraftSlimeWorld.java:171) ~[?:?]
        at com.grinderwolf.swm.plugin.SWMPlugin.createEmptyWorld(SWMPlugin.java:291) ~[?:?]
        at com.grinderwolf.swm.plugin.commands.sub.CreateWorldCmd.lambda$onCommand$1(CreateWorldCmd.java:84) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1015]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1015]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1015]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

I fixed this by removing FAWE.

**Comment by Paul19988** [comment]
This is commonly known as an issue, a work around is to have a world loaded in (A)SWM on startup at all times then you can run FAWE alongside it
