### ISSUE TITLE
Error when saving the world during server shutdown

### ISSUE THREAD

**Issue by nosooqua** [Paul19988/Advanced-Slime-World-Manager#47]
**Describe the issue**
When I stop the server world doesn't save.

**Spigot version**
Purpur version git-Purpur-1144 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugin version**
2.6.1-SNAPSHOT

**How to reproduce**
Stop Purpur server with loaded SWM world

**Crash reports (if available)**

```[18:48:14 INFO]: Stopping server
[18:48:14 INFO]: [SlimeWorldManager] Disabling SlimeWorldManager v2.6.1-SNAPSHOT
[18:48:14 INFO]: Saving players
[18:48:14 INFO]: Saving worlds
[18:48:14 INFO]: Saving chunks for level 'ServerLevel[world_lobby]'/minecraft:overworld
[18:48:14 INFO]: ThreadedAnvilChunkStorage (world_lobby): All chunks are saved
[18:48:14 INFO]: Saving world world_lobby...
[18:48:15 ERROR]: Exception stopping the server
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:823) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:510) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:465) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:166) ~[patched_1.16.5.jar:git-Purpur-1144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Purpur-1144]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.grinderwolf.swm.nms.CraftSlimeWorld.serializeCompoundTag(CraftSlimeWorld.java:344) ~[?:?]
	at com.grinderwolf.swm.nms.CraftSlimeWorld.serializeChunks(CraftSlimeWorld.java:256) ~[?:?]
	at com.grinderwolf.swm.nms.CraftSlimeWorld.serialize(CraftSlimeWorld.java:177) ~[?:?]
	at com.grinderwolf.swm.nms.v1_16_R3.CustomWorldServer.save(CustomWorldServer.java:111) ~[?:?]
	at com.grinderwolf.swm.nms.v1_16_R3.CustomWorldServer.save(CustomWorldServer.java:90) ~[?:?]
	at net.minecraft.server.v1_16_R3.MinecraftServer.saveChunks(MinecraftServer.java:841) ~[patched_1.16.5.jar:git-Purpur-1144]
	at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:931) ~[patched_1.16.5.jar:git-Purpur-1144]
	at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:778) ~[patched_1.16.5.jar:git-Purpur-1144]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1195) ~[patched_1.16.5.jar:git-Purpur-1144]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1144]
	at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by portlek** [comment]
yes, it did the same for me. I enter the /save-all command before shutting down the server and the problem goes away.

**Comment by Owen1212055** [comment]
Can confirm on latest paper server.
