### ISSUE TITLE
Generated config is literally "null"

### ISSUE THREAD

**Issue by MRtecno98** [Paul19988/Advanced-Slime-World-Manager#72]
**Describe the issue**
When the plugin starts up the first time the generated main config is literally "null"

![image](https://user-images.githubusercontent.com/20360363/136280567-21dc447b-de46-4d4b-87e6-4e18b0ace9ae.png)

This then causes the plugin to crash when it tries to load the generated config

**Spigot version**
PaperMC 1.17.1

**Plugin version**
v2.6.1-SNAPSHOT

**How to reproduce**
Just start up the server with the plugin without an already generated config

**Crash reports (if available)**
```
[22:41:39 ERROR]: Error occurred while enabling SlimeWorldManager v2.6.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.grinderwolf.swm.plugin.config.MainConfig.getUpdaterOptions()" because the return value of "com.grinderwolf.swm.plugin.config.ConfigManager.getMainConfig()" is null
 at com.grinderwolf.swm.plugin.SWMPlugin.onEnable(SWMPlugin.java:134) ~[?:?]
 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-604]
 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-604]
 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-604]
 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-604]
 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-604]
 at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-604]
 at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-604]
 at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-604]
 at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-604]
```

**Comment by zrdzn** [comment]
2.6.1 didn't worked for me on 1.17.1 either. You should download latest [build](https://dl.rapture.pw/ASWM/develop/c38026b106ae88c28e953e8a227ce76f4959bcbb/slimeworldmanager-plugin-2.6.2-SNAPSHOT.jar). I guess you have in your logs a warning that the SWM does not support Spigot v1.17 or something like that, it's at the plugin loading stage.

**Comment by MRtecno98** [comment]
Same problem with 2.6.2 too
```
[23:00:10 ERROR]: Error occurred while enabling SlimeWorldManager v2.6.2-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.grinderwolf.swm.plugin.config.MainConfig.getUpdaterOptions()" because the return value of "com.grinderwolf.swm.plugin.config.ConfigManager.getMainConfig()" is null
 at com.grinderwolf.swm.plugin.SWMPlugin.onEnable(SWMPlugin.java:134) ~[?:?]
 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-604]
 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-604]
 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-604]
 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-604]
 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-604]
 at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-604]
 at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-604]
 at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-604]
 at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-604]
```

**Comment by Paul19988** [comment]
Put this in main.yml
```
updater:
    enabled: true
    onjoinmessage: true
```

**Comment by MRtecno98** [comment]
Thanks that fixed it. Should probably fix the actual config generation though lol
