### ISSUE TITLE
IOException on world save

### ISSUE THREAD

**Issue by renvins** [Paul19988/Advanced-Slime-World-Manager#95]
**Describe the issue**
This error happens only sometimes, not often

**Spigot version**
1.16.5
**Plugin version**
Latest version
**How to reproduce**
Just save a world a few times
**Crash reports (if available)**
`[19:44:30] [SWM Pool Thread #3/INFO]: Saving world KEVVOOOO15-station...
[19:44:30] [Server thread/INFO]: ThreadedAnvilChunkStorage (KEVVOOOO15-station): All chunks are saved
[19:44:30] [SWM Pool Thread #3/WARN]: java.io.IOException: Bad file descriptor
[19:44:30] [SWM Pool Thread #3/WARN]: 	at java.base/java.io.RandomAccessFile.setLength(Native Method)
[19:44:30] [SWM Pool Thread #3/WARN]: 	at com.grinderwolf.swm.plugin.loaders.file.FileLoader.saveWorld(FileLoader.java:102)
[19:44:30] [SWM Pool Thread #3/WARN]: 	at com.grinderwolf.swm.nms.v11645.CustomWorldServer.save(CustomWorldServer.java:103)
[19:44:30] [SWM Pool Thread #3/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[19:44:30] [SWM Pool Thread #3/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[19:44:30] [SWM Pool Thread #3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)`

**Comment by ComputerNerd100** [comment]
Thanks for reporting this - will look into this for you, my initial guess is a concurrency issue with repeated saving.
Can you confirm if you've experienced this with any other loaders (e.g. MySQL) or just with the FileLoader?

**Comment by renvins** [comment]
> Thanks for reporting this - will look into this for you, my initial guess is a concurrency issue with repeated saving. Can you confirm if you've experienced this with any other loaders (e.g. MySQL) or just with the FileLoader?

I've tried only with FileLoader

**Comment by renvins** [comment]
The file, after this error, corrupts and has lenght 0
